### ISSUE TITLE
Context Danger.java

### ISSUE THREAD

**Issue by MarcPrats** [frco9/IF322#1]
J'ai commencé à implémenter le Danger.java mais, il n'est pas du tout opérationnel. Si j'ai push, c'est plus pour montrer ce vers quoi je me dirige.

**Comment by frco9** [comment]
Yop, merci d'avoir avancé ! Désolé de pas y avoir touché avant. 
J'ai quelques soucis avec les Spécifications, je vais essayer de corriger les trucs qui me vont pas et commit. 
Notamment la gestion du temps avec une horloge. Ça me parait compliqué, par exemple dans ton implémentation, à chaque appel de la fonction `onTickSecondFromClock` tu remets le compteur `t_inactive` à 0 donc ton programme ne déclenchera jamais le Remind ! A moins que je n'ai pas tout compris :/ !

**Comment by frco9** [comment]
Je pense qu'un `Timer`serait plus adapté, non ? Encore faut-il que je comprenne comment ça fonctionne...

**Comment by brambaud** [comment]
J'ai push sur une branche nommée\* ben\* une suite du Danger.java qu'avait
proposé Marc dans un premier temps.

Par contre, il y a un truc que je ne suis pas sur d'avoir compris. Dans le
context Danger, on retourne la valeur du danger sous forme de _DangerLevel_
: ZERO, REMIND, ALERT, STOP. Dans les controller RemindUser et StopCooker,
on lit la valeur du danger grâce à _DangerValue danger. *En revanche, à
aucun moment on ne set la valeur de *DangerValue danger_ dans le code et je
ne vois pas où ça peut se faire.

J'ai aussi l'impression d'avoir un petit problème avec la gestion du temps.

2015-01-03 12:21 GMT+01:00 Jérémie Foucault notifications@github.com:

**Comment by frco9** [comment]
Ca se fait pas tout seul le binding de la valeur de danger entre le Context et le Controller ? On a un moyen de tester ce qu'on fait ou pas ? 
Ça change quoi le fait de always, maybe, no publier dans le context des spécifications car pour moi il faut publier !?

**Comment by brambaud** [comment]
Je ne sais pas d’où ma question.
Pour le test, ça devrait être avec JUnit comme dans l'exemple qu'il nous
avait montré.

Pour le publish je ne sais pas trop, j'avais hésité à changer et comme la
documentation de DiaSuite\* n'a pas pas beaucoup aidée, j'ai
décidé de laisser comme ça pour le moment.

*Extrait Doc de DiaSuite
http://phoenix.inria.fr/research-projects/diasuite/148-diasuite-manual#d5e43

Sensors are proactive or reactive components whereas contexts, controllers
and actuators are always reactive. All computations are thus initiated by a
publish/subscribe interaction from the sensors. A context or a controller
is defined by a list of interaction contracts separated by commas.

An interaction contract is composed of three parts:
1. *The activation condition \* . A context can only be activated either
   by a data requirement from a parent context ( when required ) or a new
   value published from either a context or a sensor (e.g., when provided
   Presence , when provided motion from MotionDetector ). A controller can
   only be activated by a new value from a context (e.g., when provided
   Presence ) ;
2. _The data requirements list_ . A context can require data from
   sensors or contexts (e.g., get motion from MotionDetector, Presence ). A
   controller can only require data from contexts (e.g., get Presence ) ;
3. _The emission_ . When activated, a context can either _always_ or
   _maybe_ or _never_ publishes a new value ( corresponding
   respectively to always
   publish , maybe publish and no publish declarations). For a controller,
   the emission part corresponds to a list of entity actions that the
   controller can call (e.g., do SendMessage on TvMessenger).

En revanche, j'ai l'impression que l'on s'y est peut-être mal pris.

Le 3 janvier 2015 15:56, Jérémie Foucault notifications@github.com a
écrit :

**Comment by frco9** [comment]
Ok, ouep j'avais vu la doc mais bon c'est pas non plus super explicite. Mais j'ai ma réponse : c'est le type de retour des méthodes implémentés dans le contexte qui change. Donc à mon avis le binding est fait automatiquement vu que ce qui est publié dans le contexte est de type `DangerValue`, le contrôleur récupère donc les bonnes valeurs !? 
J'ai modifié la taxonomie et j'essaie avec des timer. J'ai fait une branche aussi je comiterai quand j'aurais un truc potable à mon gout. 

C'est à rendre quand ? Car d'après le syllabus la demo des "Applications" c'est Vendredi, mais on a 2*2h40 avec eux Mardi, donc on pourra leur/lui poser des question mardi matin au pire ?

**Comment by MarcPrats** [comment]
Bonsoir,
Je viens de lire vos commentaires et je pense que le mieux, cest quon en reparle lundi ou mardi.
Concernant mon contexte, il est faux, je voulais seulement vous montrer la tete de mon code
